[tox]
envlist = py38, py39, py310, py311, py312, black

[travis]
python =
    3.12: py312
    3.11: py311
    3.10: py310
    3.9: py39
    3.8: py38

[testenv:black]
basepython = python
deps = black
commands = black --check src tests

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
deps =
    -r{toxinidir}/requirements_dev.txt
; If you want to make tox run the tests with the same versions, create a
; requirements.txt with the pinned versions and uncomment the following line:
;     -r{toxinidir}/requirements.txt
commands =
    pip install -U pip
    pytest --basetemp={envtmpdir}

[testenv:qiskit-{v1.4, v2.0, latest}]
description =
    Invoke pytest to run automated tests for all Qiskit 1.x, 2.x, and latest versions.
base_python = py310: python3.10
deps =
    v1.4: qiskit >= 1.4, <1.5
    v1.4: qiskit-aer >= 0.15, < 0.16  
    v2.0: qiskit >= 2.0, <2.1
    v2.0: qiskit-aer >= 0.17, < 0.18
    latest: qiskit
    latest: qiskit-aer  
extras =
    testing
commands =
    pip list | grep qiskit
    pytest --basetemp={envtmpdir}
