[tox]
envlist = black, py39, py310, py311, py312, qiskit-v1, qiskit-v2, qiskit-latest

[travis]
python =
    3.12: py312
    3.11: py311
    3.10: py310
    3.9: py39

[testenv:black]
basepython = python
deps = 
    -r{toxinidir}/requirements_dev.txt
commands = black --check src tests

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
deps =
    -r{toxinidir}/requirements_dev.txt
; If you want to make tox run the tests with the same versions, create a
; requirements.txt with the pinned versions and uncomment the following line:
;     -r{toxinidir}/requirements.txt
commands =
    pip install -U pip
    pytest --basetemp={envtmpdir}

[testenv:qiskit-{v1, v2, latest}]
description =
    Invoke pytest to run automated tests for all Qiskit 1.x, 2.x, and latest versions.
base_python = py312: python3.12
deps =
    -r{toxinidir}/requirements_dev.txt
    v1: qiskit < 2.0
    v1: qiskit-aer >= 0.15, < 0.16  
    v2: qiskit >= 2.0, < 2.1
    v2: qiskit-aer >= 0.17, < 0.18
    latest: qiskit > 2.1
    latest: qiskit-aer >= 0.17 
extras =
    testing
commands =
    pip list | grep qiskit
    pytest --basetemp={envtmpdir}

[testenv:format]
description =
    Format the codebase.
skip_install = True
changedir = {toxinidir}
deps =
    -r{toxinidir}/requirements_dev.txt
commands =
    python -m black src tests