name: Upload package to PyPI and publish documentation

on:
  release:
    types: [published]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: uv pip install --constraint requirements_dev.txt --editable .[cicd]
      - name: Build distribution
        run: uv build
      - name: Store distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist

  push_to_pypi:
    runs-on: ubuntu-latest
    needs:
    - build
    environment:
      name: pypi
      url: https://pypi.org/p/iqm-qiskit-qir
    permissions:
      id-token: write
    steps:
      - name: Download distribution packages
        uses: actions/download-artifact@v4
      - name: Publish distribution packages to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            attestations: false

  publish_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
      - name: Checkout latest tagged commit
        run: |
          git checkout $(git describe --tags --abbrev=0)
      - name: Install dependencies
        run: |
          uv pip install --constraint requirements_dev.txt --editable .[cicd,docs]
          sudo apt-get install graphviz
          sudo apt-get install sphinx
      - name: Build docs
        run: |
          sphinx-build -b html docs/ build/sphinx/html
          touch build/sphinx/html/.nojekyll  # allow underscores in URL path
          # remove unnecessary build files
          sudo rm -rf build/sphinx/html/.doctrees
      - name: Publish to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build/sphinx/html
          force: false
